### ISSUE TITLE
Failing to comply with the licence

### ISSUE THREAD

**Issue by Wild1145** [tylerhyperHD/EpicFreedomMod#2]
As per section 10 of the GNU GPL V3 you may not sub-licence or impose any additional restrictions as a downstream project of the main TotalFreedomMod. You can read the full licence for yourself here: http://www.gnu.org/licenses/gpl-3.0.txt . By imposing additional restrictions as you have you are in breach of the licence and as such breaking the law. Please make the appropriate changes.

**Comment by tylerhyperHD** [comment]
As of currently, we are attempting to get written approval to sub-license
this. If we fail to do this, we will remove the sub-license provided. Thank
you for your patience.

**Comment by Wild1145** [comment]
As it stands the license is being broken. You need to revert such changes until written approval is issued.

**Comment by tylerhyperHD** [comment]
Okay the next commit will be at 5:00PM (UTC-5)

**Comment by tylerhyperHD** [comment]
Latest commit should have fixed the license.
